name: loco-dev

services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: loco
      POSTGRES_DB: loco_test_development
      POSTGRES_PASSWORD: "loco"
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379
